# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BreakPointIndex
                                 A QGIS plugin
 Plugin for calculating Break Point Index landscape metric
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-21
        copyright            : (C) 2025 by gudmandras
        email                : gudmandras@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'gudmandras'
__date__ = '2025-12-21'
__copyright__ = '(C) 2025 by gudmandras'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BreakPointIndex class from file BreakPointIndex.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .break_pointer import BreakPointIndexPlugin
    return BreakPointIndexPlugin(iface)
